### ISSUE TITLE
Le groupe politique par session

### ISSUE THREAD

**Issue by yrochat** [douglas-watson/parl-scraping#6]
C'est secondaire, mais je m'en suis rendu compte alors que je triais dans le réseau les conseiller-ère-s par groupe politique : l'API ne retourne que le groupe politique actuel. Quelqu'un qui aura siégé sur plusieurs exercices et changé de groupe politique (parfois ce n'est que le nom qui change) n'aura sur sa biographie que le dernier profil qui s'affiche. 

Pour résoudre ce problème, il faudra obtenir les listes pour chaque exercice (+ nouveaux entrants + év. changement de groupe politique… arf).

**Comment by sijow** [comment]
Sauf erreur on a le groupe politique dans chaque intervention? (contrairement au parti qu'on a seulement dans les données bio)

**Comment by yrochat** [comment]
Bien vu ! Je me basais sur les bios, mais c'est plus simple de passer par là. Merci !
